server:
  port: 1808
  name: users

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.nwolfhub.org/realms/id/protocol/openid-connect/certs
          issuer-uri: https://login.nwolfhub.org/realms/id
          client: users
          clientsecret: your-client-secret
database:
  host: 127.0.0.1
  port: 5432
  name: users
  credentials:
    username: user
    password: password
users:
  max-notes: 1000